import { createContext, useContext, useState, ReactNode, useEffect } from "react";

export type Language = "en" | "hi";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

// Translations
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    "common.home": "Home",
    "common.login": "Login",
    "common.logout": "Logout",
    "common.dashboard": "Dashboard",
    "common.settings": "Settings",
    "common.profile": "Profile",
    "common.language": "Language",
    "common.english": "English",
    "common.hindi": "हिंदी",
    "common.submit": "Submit",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.warning": "Warning",
    "common.info": "Information",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.view": "View",
    "common.download": "Download",
    "common.upload": "Upload",
    "common.noData": "No data available",
    "common.confirmation": "Confirmation",
    "common.areYouSure": "Are you sure?",

    // Auth
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.phone": "Phone Number",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.forgotPassword": "Forgot Password?",
    "auth.rememberMe": "Remember Me",
    "auth.invalidCredentials": "Invalid email or password",
    "auth.loginSuccess": "Logged in successfully",
    "auth.logoutSuccess": "Logged out successfully",
    "auth.newHire": "New Hire? Start Here",
    "auth.selectRole": "Select your role and sign in to continue",
    "auth.superAdmin": "Super Admin",
    "auth.superAdminDesc": "Full system access & control",
    "auth.outlet": "Outlet",
    "auth.outletDesc": "Manage store employees & deactivation",
    "auth.fieldCoach": "Field Coach",
    "auth.fieldCoachDesc": "Approve onboarding & deactivation",
    "auth.staffLogin": "Staff Login",

    // Index Page
    "index.joinFamily": "Join the Burger Singh Family",
    "index.startJourney": "Start Your Journey",
    "index.withUs": "With Us Today",
    "index.subtitle": "Complete your onboarding in minutes. Select your role, verify your identity, and get started!",
    "index.quickProcess": "Quick Process",
    "index.quickProcessDesc": "Complete onboarding in under 10 minutes",
    "index.secureVerification": "Secure Verification",
    "index.secureVerificationDesc": "DigiLocker powered Aadhaar verification",
    "index.instantAccess": "Instant Access",
    "index.instantAccessDesc": "Get LMS access immediately after approval",
    "index.selectYourRole": "Select Your Role",
    "index.choosePosition": "Choose the position you're applying for",
    "index.selectOutlet": "Select Outlet",
    "index.chooseOutlet": "Choose the outlet where you'll be working",
    "index.startOnboarding": "Start Onboarding",
    "index.loadingRoles": "Loading roles...",
    "index.terms": "By continuing, you agree to our Terms of Service and Privacy Policy",
    "index.allRightsReserved": "All rights reserved.",
    "index.pleaseSelectRole": "Please select a role",
    "index.pleaseSelectOutlet": "Please select an outlet",

    // Onboarding
    "onboarding.title": "Onboarding",
    "onboarding.welcome": "Welcome to Burger Singh",
    "onboarding.step1": "Personal Information",
    "onboarding.step2": "Employment Details",
    "onboarding.step3": "Document Verification",
    "onboarding.step4": "Review & Submit",
    "onboarding.firstName": "First Name",
    "onboarding.lastName": "Last Name",
    "onboarding.email": "Email Address",
    "onboarding.phone": "Phone Number",
    "onboarding.dateOfBirth": "Date of Birth",
    "onboarding.address": "Address",
    "onboarding.city": "City",
    "onboarding.state": "State",
    "onboarding.postalCode": "Postal Code",
    "onboarding.resume": "Resume",
    "onboarding.uploadDocument": "Upload Document",
    "onboarding.selectOutlet": "Select Outlet",
    "onboarding.selectRole": "Select Role",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.welcome": "Welcome",
    "dashboard.todayStats": "Today's Stats",
    "dashboard.totalApplications": "Total Applications",
    "dashboard.pendingApprovals": "Pending Approvals",
    "dashboard.completedApplications": "Completed Applications",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.applicationList": "Application List",
    "dashboard.status": "Status",
    "dashboard.applicantName": "Applicant Name",
    "dashboard.position": "Position",
    "dashboard.appliedOn": "Applied On",
    "dashboard.action": "Action",
    "dashboard.approve": "Approve",
    "dashboard.reject": "Reject",
    "dashboard.review": "Review",
    "dashboard.pending": "Pending",
    "dashboard.approved": "Approved",
    "dashboard.rejected": "Rejected",
    "dashboard.inProgress": "In Progress",
    "dashboard.outletDashboard": "Outlet Dashboard",
    "dashboard.fieldCoachDashboard": "Field Coach Dashboard",
    "dashboard.totalOnboardings": "Total Onboardings",
    "dashboard.activeEmployees": "Active Employees",
    "dashboard.totalDeactivations": "Total Deactivations",
    "dashboard.deactivationRequests": "Deactivation Requests",
    "dashboard.onboardingApplications": "Onboarding Applications",
    "dashboard.employeeManagement": "Employee Management",
    "dashboard.initiateOnboarding": "Initiate Onboarding",
    "dashboard.requestDeactivation": "Request Deactivation",
    "dashboard.deactivationManagement": "Deactivation Management",
    "dashboard.completed": "Completed",
    "dashboard.onboarding": "Onboarding",
    "dashboard.employees": "Employees",
    "dashboard.deactivation": "Deactivation",
    "dashboard.startNewOnboarding": "Start New Onboarding",
    "dashboard.searchByName": "Search by name, phone...",
    "dashboard.recentOnboardings": "Recent Onboardings",
    "dashboard.storeEmployees": "Store Employees",
    "dashboard.deactivate": "Deactivate",
    "dashboard.joined": "Joined",
    "dashboard.waitingApproval": "Waiting for Field Coach approval",
    "dashboard.onboardingDetails": "Onboarding Details",
    "dashboard.completeInfo": "Complete information for",
    "dashboard.basicInformation": "Basic Information",
    "dashboard.fullName": "Full Name",
    "dashboard.role": "Role",
    "dashboard.outlet": "Outlet",
    "dashboard.startedAt": "Started At",
    "dashboard.currentStatus": "Current Status",
    "dashboard.nextSteps": "Next Steps",
    "dashboard.submitDeactivation": "Submit a deactivation request for",
    "dashboard.sentToCoach": "This will be sent to the Field Coach for approval.",
    "dashboard.reasonForDeactivation": "Reason for Deactivation",
    "dashboard.enterReason": "Enter the reason for deactivation...",
    "dashboard.submitRequest": "Submit Request",
    "dashboard.close": "Close",
    "dashboard.draft": "Draft",
    "dashboard.submitted": "Submitted",
    "dashboard.active": "Active",
    "dashboard.inactive": "Inactive",
    "dashboard.pendingDeactivation": "Pending Deactivation",
    "dashboard.statusDraft": "Employee has started but not completed the onboarding form.",
    "dashboard.statusInProgress": "Employee is currently completing the onboarding process.",
    "dashboard.statusSubmitted": "Onboarding form has been submitted and is awaiting review.",
    "dashboard.statusPendingApproval": "Waiting for Field Coach approval.",
    "dashboard.statusApproved": "Onboarding has been approved!",
    "dashboard.statusRejected": "Onboarding was rejected by the Field Coach.",
    "dashboard.nextStepDraft": "The employee needs to complete and submit the onboarding form.",
    "dashboard.nextStepInProgress": "The employee needs to complete all onboarding steps.",
    "dashboard.nextStepSubmitted": "The application is under review by the Field Coach.",
    "dashboard.nextStepPendingApproval": "The Field Coach will review this application soon.",
    "dashboard.nextStepApproved": "This employee can now access the LMS and start working.",
    "dashboard.nextStepRejected": "You may need to contact the Field Coach for more details or restart the onboarding process.",
    "dashboard.pendingReview": "Pending Review",
    "dashboard.onboardingApprovals": "Onboarding Approvals",
    "dashboard.searchByNamePhoneOutlet": "Search by name, phone, or outlet...",
    "dashboard.all": "All",
    "dashboard.aadhaarVerified": "Aadhaar Verified",
    "dashboard.panVerified": "PAN Verified",
    "dashboard.aadhaarNotVerified": "Aadhaar Not Verified",
    "dashboard.viewFullDetails": "View Full Details",
    "dashboard.viewDocuments": "View Documents",
    "dashboard.requestedBy": "Requested by",
    "dashboard.date": "Date",
    "dashboard.reason": "Reason",
    "dashboard.approveApplication": "Approve Application",
    "dashboard.rejectApplication": "Reject Application",
    "dashboard.approvingCreatesLMS": "Approving {name}'s application will create their LMS account automatically.",
    "dashboard.provideRejectionReason": "Please provide a reason for rejecting {name}'s application.",
    "dashboard.enterRejectionReason": "Enter rejection reason...",
    "dashboard.approveAndCreateLMS": "Approve & Create LMS",
    "dashboard.approveDeactivation": "Approve Deactivation",
    "dashboard.rejectDeactivation": "Reject Deactivation",
    "dashboard.approvingDeactivatesLMS": "Approving will deactivate {name}'s LMS account.",
    "dashboard.rejectingKeepsActive": "Rejecting will keep {name}'s account active.",
    "dashboard.enterReasonForRejection": "Enter reason for rejection...",
    "dashboard.completeApplicationDetails": "Complete Application Details",
    "dashboard.fullInformationFor": "Full information for",
    "dashboard.personalInformation": "Personal Information",
    "dashboard.gender": "Gender",
    "dashboard.dateOfBirth": "Date of Birth",
    "dashboard.maritalStatus": "Marital Status",
    "dashboard.bloodGroup": "Blood Group",
    "dashboard.notProvided": "Not Provided",
    "dashboard.contactInformation": "Contact Information",
    "dashboard.phone1": "Phone 1",
    "dashboard.phone2": "Phone 2",
    "dashboard.verified": "Verified",
    "dashboard.currentAddress": "Current Address",
    "dashboard.permanentAddress": "Permanent Address",
    "dashboard.education": "Education",
    "dashboard.qualification": "Qualification",
    "dashboard.specialization": "Specialization",
    "dashboard.educationStatus": "Status",
    "dashboard.workExperience": "Work Experience",
    "dashboard.totalExperience": "Total Experience",
    "dashboard.years": "years",
    "dashboard.lastDesignation": "Last Designation",
    "dashboard.employmentDetails": "Employment Details",
    "dashboard.store": "Store",
    "dashboard.storeCode": "Store Code",
    "dashboard.storeName": "Store Name",
    "dashboard.dateOfJoining": "Date of Joining",
    "dashboard.fieldCoach": "Field Coach",
    "dashboard.idVerification": "ID & Verification",
    "dashboard.aadhaar": "Aadhaar",
    "dashboard.pan": "PAN",
    "dashboard.uniformSize": "Uniform Size",
    "dashboard.tshirt": "T-shirt",
    "dashboard.lower": "Lower",
    "dashboard.vaccinationStatus": "Vaccination Status",
    "dashboard.covidVaccinated": "COVID-19 Vaccinated",
    "dashboard.covidNotVaccinated": "COVID-19 Not Vaccinated",
    "dashboard.previousEmploymentHistory": "Previous Employment History",
    "dashboard.workedPreviously": "This applicant has worked at Burger Singh previously. Review their employment history below.",
    "dashboard.deactivated": "Deactivated",
    "dashboard.terminated": "Terminated",
    "dashboard.cancel": "Cancel",
    "dashboard.email": "Email",

    // Admin
    "admin.title": "Admin Dashboard",
    "admin.dashboard": "Dashboard",
    "admin.employees": "Employees",
    "admin.outlets": "Outlets",
    "admin.fieldCoaches": "Field Coaches",
    "admin.roles": "Roles",
    "admin.settings": "Settings",
    "admin.superAdmin": "Super Admin",
    "admin.totalUsers": "Total Users",
    "admin.pendingApprovals": "Pending Approvals",
    "admin.activeOutlets": "Active Outlets",
    "admin.totalRoles": "Total Roles",
    "admin.quickActions": "Quick Actions",
    "admin.manageOutlets": "Manage Outlets",
    "admin.manageRoles": "Manage Roles",
    "admin.viewEmployees": "View Employees",
    "admin.exportData": "Export Data",
    "admin.recentOutlets": "Recent Outlets",
    "admin.roleDistribution": "Role Distribution",
    "admin.users": "users",
    "admin.allUsers": "All Users",
    "admin.longPending": "Long Pending",
    "admin.missingDocs": "Missing Docs",
    "admin.rehire": "Rehire",
    "admin.searchPlaceholder": "Search by name, phone, Aadhaar, or PAN...",
    "admin.allStores": "All Stores",
    "admin.store": "Store",
    "admin.allCoaches": "All Coaches",
    "admin.allStatus": "All Status",
    "admin.exportCSV": "Export CSV",
    "admin.exportUsers": "Export Users",
    "admin.loadingEmployees": "Loading employees...",
    "admin.employee": "Employee",
    "admin.contact": "Contact",
    "admin.verification": "Verification",
    "admin.actions": "Actions",
    "admin.copyEmployeeURL": "Copy Employee URL",
    "admin.initiateRehire": "Initiate Rehire",
    "admin.deactivate": "Deactivate",
    "admin.terminate": "Terminate",
    "admin.noEmployeesFound": "No employees found",
    "admin.addOutlet": "Add Outlet",
    "admin.outletName": "Outlet Name",
    "admin.code": "Code",
    "admin.employeeCount": "Employee Count",
    "admin.createdOn": "Created On",
    "admin.assignFieldCoach": "Assign Field Coach",
    "admin.noFieldCoachAssigned": "No field coach assigned",
    "admin.editOutlet": "Edit Outlet",
    "admin.deleteOutlet": "Delete Outlet",
    "admin.noOutletsFound": "No outlets found",
    "admin.addFieldCoach": "Add Field Coach",
    "admin.assignedOutlets": "Assigned Outlets",
    "admin.noOutletsAssigned": "No outlets assigned",
    "admin.editFieldCoach": "Edit Field Coach",
    "admin.deleteFieldCoach": "Delete Field Coach",
    "admin.noFieldCoachesFound": "No field coaches found",
    "admin.addRole": "Add Role",
    "admin.description": "Description",
    "admin.userCount": "User Count",
    "admin.created": "Created",
    "admin.editRole": "Edit Role",
    "admin.deleteRole": "Delete Role",
    "admin.noRolesFound": "No roles found",
    "admin.terminateEmployee": "Terminate Employee",
    "admin.terminatingWarning": "Terminating {name} will permanently deactivate their account and LMS access. This action cannot be undone.",
    "admin.terminationReason": "Termination Reason",
    "admin.deactivateEmployee": "Deactivate Employee",
    "admin.deactivatingWarning": "Deactivating {name} will suspend their account and LMS access. They can be rehired later.",
    "admin.deactivationReason": "Deactivation Reason",
    "admin.createOutlet": "Create Outlet",
    "admin.outletInformation": "Outlet Information",
    "admin.enterOutletName": "Enter outlet name",
    "admin.enterOutletCode": "Enter outlet code (e.g., BS-CP-001)",
    "admin.enterEmail": "Enter email",
    "admin.enterPassword": "Enter password",
    "admin.enterPhone": "Enter phone number",
    "admin.address": "Address",
    "admin.enterAddress": "Enter address",
    "admin.city": "City",
    "admin.enterCity": "Enter city",
    "admin.state": "State",
    "admin.enterState": "Enter state",
    "admin.pincode": "Pincode",
    "admin.enterPincode": "Enter pincode",
    "admin.selectFieldCoach": "Select field coach",
    "admin.none": "None",
    "admin.create": "Create",
    "admin.update": "Update",
    "admin.updateOutlet": "Update Outlet",
    "admin.deleteOutletConfirm": "Are you sure you want to delete {name}? This action cannot be undone.",
    "admin.createFieldCoach": "Create Field Coach",
    "admin.fieldCoachInformation": "Field Coach Information",
    "admin.enterName": "Enter name",
    "admin.noOutletsAvailable": "No outlets available",
    "admin.updateFieldCoach": "Update Field Coach",
    "admin.deleteFieldCoachConfirm": "Are you sure you want to delete {name}? All assigned outlets will be unassigned.",
    "admin.createRole": "Create Role",
    "admin.roleInformation": "Role Information",
    "admin.roleName": "Role Name",
    "admin.enterRoleName": "Enter role name",
    "admin.roleDescription": "Role Description",
    "admin.enterRoleDescription": "Enter role description",
    "admin.updateRole": "Update Role",
    "admin.deleteRoleConfirm": "Are you sure you want to delete the {name} role?",
    "admin.uploadedDocuments": "Uploaded Documents",
    "admin.allDocumentsSubmitted": "All documents submitted by {name}",
    "admin.livePhoto": "Live Photo",
    "admin.clickToOpenFullSize": "Click to open full size",
    "admin.educationCertificate": "Education Certificate",
    "admin.experienceDocument": "Experience Document",
    "admin.idDocuments": "ID Documents (Aadhaar/PAN Copy)",
    "admin.panDocument": "PAN Document",
    "admin.otherCertificates": "Other Certificates",
    "admin.noDocumentsUploaded": "No documents uploaded",

    // Errors
    "error.pageNotFound": "Oops! Page not found",
    "error.unauthorized": "Access Denied",
    "error.somethingWentWrong": "Looks like this page went out for a burger break. Let's get you back on track!",
    "error.tryAgain": "Try Again",
    "error.goHome": "Home Page",
    "error.contactSupport": "You don't have permission to access this page. Please contact your administrator if you believe this is an error.",
  },
  hi: {
    // Common
    "common.home": "होम",
    "common.login": "लॉगिन",
    "common.logout": "लॉग आउट",
    "common.dashboard": "डैशबोर्ड",
    "common.settings": "सेटिंग्स",
    "common.profile": "प्रोफ़ाइल",
    "common.language": "भाषा",
    "common.english": "English",
    "common.hindi": "हिंदी",
    "common.submit": "सबमिट करें",
    "common.cancel": "रद्द करें",
    "common.save": "सहेजें",
    "common.delete": "हटाएं",
    "common.edit": "संपादित करें",
    "common.back": "वापस",
    "common.next": "अगला",
    "common.previous": "पिछला",
    "common.loading": "लोड हो रहा है...",
    "common.error": "त्रुटि",
    "common.success": "सफल",
    "common.warning": "चेतावनी",
    "common.info": "जानकारी",
    "common.search": "खोज",
    "common.filter": "फिल्टर",
    "common.sort": "सॉर्ट करें",
    "common.view": "देखें",
    "common.download": "डाउनलोड",
    "common.upload": "अपलोड",
    "common.noData": "कोई डेटा उपलब्ध नहीं",
    "common.confirmation": "पुष्टि",
    "common.areYouSure": "क्या आप सुनिश्चित हैं?",

    // Auth
    "auth.email": "ईमेल",
    "auth.password": "पासवर्ड",
    "auth.phone": "फोन नंबर",
    "auth.signIn": "साइन इन करें",
    "auth.signUp": "साइन अप करें",
    "auth.forgotPassword": "पासवर्ड भूल गए?",
    "auth.rememberMe": "मुझे याद रखें",
    "auth.invalidCredentials": "अमान्य ईमेल या पासवर्ड",
    "auth.loginSuccess": "सफलतापूर्वक लॉगिन किया गया",
    "auth.logoutSuccess": "सफलतापूर्वक लॉग आउट किया गया",
    "auth.newHire": "नया कर्मचारी? यहाँ से शुरू करें",
    "auth.selectRole": "अपनी भूमिका चुनें और जारी रखने के लिए साइन इन करें",
    "auth.superAdmin": "सुपर एडमिन",
    "auth.superAdminDesc": "पूर्ण सिस्टम एक्सेस और नियंत्रण",
    "auth.outlet": "आउटलेट",
    "auth.outletDesc": "स्टोर कर्मचारियों और निष्क्रियता का प्रबंधन करें",
    "auth.fieldCoach": "फील्ड कोच",
    "auth.fieldCoachDesc": "ऑनबोर्डिंग और निष्क्रियता को स्वीकृत करें",
    "auth.staffLogin": "स्टाफ लॉगिन",

    // Index Page
    "index.joinFamily": "बर्गर सिंह परिवार में शामिल हों",
    "index.startJourney": "अपनी यात्रा शुरू करें",
    "index.withUs": "आज हमारे साथ",
    "index.subtitle": "मिनटों में अपनी ऑनबोर्डिंग पूरी करें। अपनी भूमिका चुनें, अपनी पहचान सत्यापित करें, और शुरू करें!",
    "index.quickProcess": "त्वरित प्रक्रिया",
    "index.quickProcessDesc": "10 मिनट से कम में ऑनबोर्डिंग पूरी करें",
    "index.secureVerification": "सुरक्षित सत्यापन",
    "index.secureVerificationDesc": "डिजिलॉकर संचालित आधार सत्यापन",
    "index.instantAccess": "तत्काल पहुंच",
    "index.instantAccessDesc": "अनुमोदन के तुरंत बाद LMS एक्सेस प्राप्त करें",
    "index.selectYourRole": "अपनी भूमिका चुनें",
    "index.choosePosition": "वह पद चुनें जिसके लिए आप आवेदन कर रहे हैं",
    "index.selectOutlet": "आउटलेट चुनें",
    "index.chooseOutlet": "वह आउटलेट चुनें जहां आप काम करेंगे",
    "index.startOnboarding": "ऑनबोर्डिंग शुरू करें",
    "index.loadingRoles": "भूमिकाएं लोड हो रही हैं...",
    "index.terms": "जारी रखकर, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत हैं",
    "index.allRightsReserved": "सर्वाधिकार सुरक्षित।",
    "index.pleaseSelectRole": "कृपया एक भूमिका चुनें",
    "index.pleaseSelectOutlet": "कृपया एक आउटलेट चुनें",

    // Onboarding
    "onboarding.title": "ऑनबोर्डिंग",
    "onboarding.welcome": "बर्गर सिंह में स्वागत है",
    "onboarding.step1": "व्यक्तिगत जानकारी",
    "onboarding.step2": "रोजगार विवरण",
    "onboarding.step3": "दस्तावेज़ सत्यापन",
    "onboarding.step4": "समीक्षा और सबमिट करें",
    "onboarding.firstName": "पहला नाम",
    "onboarding.lastName": "अंतिम नाम",
    "onboarding.email": "ईमेल पता",
    "onboarding.phone": "फोन नंबर",
    "onboarding.dateOfBirth": "जन्म की तारीख",
    "onboarding.address": "पता",
    "onboarding.city": "शहर",
    "onboarding.state": "राज्य",
    "onboarding.postalCode": "पिन कोड",
    "onboarding.resume": "रिज्यूमे",
    "onboarding.uploadDocument": "दस्तावेज़ अपलोड करें",
    "onboarding.selectOutlet": "आउटलेट चुनें",
    "onboarding.selectRole": "भूमिका चुनें",

    // Dashboard
    "dashboard.title": "डैशबोर्ड",
    "dashboard.welcome": "स्वागत है",
    "dashboard.todayStats": "आज के आंकड़े",
    "dashboard.totalApplications": "कुल आवेदन",
    "dashboard.pendingApprovals": "लंबित स्वीकृतियां",
    "dashboard.completedApplications": "पूर्ण आवेदन",
    "dashboard.recentActivity": "हाल की गतिविधि",
    "dashboard.applicationList": "आवेदन सूची",
    "dashboard.status": "स्थिति",
    "dashboard.applicantName": "आवेदक का नाम",
    "dashboard.position": "पद",
    "dashboard.appliedOn": "पर आवेदन किया",
    "dashboard.action": "कार्रवाई",
    "dashboard.approve": "स्वीकृत करें",
    "dashboard.reject": "अस्वीकार करें",
    "dashboard.review": "समीक्षा करें",
    "dashboard.pending": "लंबित",
    "dashboard.approved": "स्वीकृत",
    "dashboard.rejected": "अस्वीकार",
    "dashboard.inProgress": "प्रगति में है",
    "dashboard.outletDashboard": "आउटलेट डैशबोर्ड",
    "dashboard.fieldCoachDashboard": "फील्ड कोच डैशबोर्ड",
    "dashboard.totalOnboardings": "कुल ऑनबोर्डिंग",
    "dashboard.activeEmployees": "सक्रिय कर्मचारी",
    "dashboard.totalDeactivations": "कुल निष्क्रियता",
    "dashboard.deactivationRequests": "निष्क्रियता अनुरोध",
    "dashboard.onboardingApplications": "ऑनबोर्डिंग आवेदन",
    "dashboard.employeeManagement": "कर्मचारी प्रबंधन",
    "dashboard.initiateOnboarding": "ऑनबोर्डिंग शुरू करें",
    "dashboard.requestDeactivation": "निष्क्रियता अनुरोध करें",
    "dashboard.deactivationManagement": "निष्क्रियता प्रबंधन",
    "dashboard.completed": "पूर्ण",
    "dashboard.onboarding": "ऑनबोर्डिंग",
    "dashboard.employees": "कर्मचारी",
    "dashboard.deactivation": "निष्क्रियता",
    "dashboard.startNewOnboarding": "नई ऑनबोर्डिंग शुरू करें",
    "dashboard.searchByName": "नाम, फोन से खोजें...",
    "dashboard.recentOnboardings": "हाल की ऑनबोर्डिंग",
    "dashboard.storeEmployees": "स्टोर कर्मचारी",
    "dashboard.deactivate": "निष्क्रिय करें",
    "dashboard.joined": "शामिल हुए",
    "dashboard.waitingApproval": "फील्ड कोच अनुमोदन की प्रतीक्षा में",
    "dashboard.onboardingDetails": "ऑनबोर्डिंग विवरण",
    "dashboard.completeInfo": "के लिए पूर्ण जानकारी",
    "dashboard.basicInformation": "मूल जानकारी",
    "dashboard.fullName": "पूरा नाम",
    "dashboard.role": "भूमिका",
    "dashboard.outlet": "आउटलेट",
    "dashboard.startedAt": "शुरू किया",
    "dashboard.currentStatus": "वर्तमान स्थिति",
    "dashboard.nextSteps": "अगले कदम",
    "dashboard.submitDeactivation": "के लिए निष्क्रियता अनुरोध सबमिट करें",
    "dashboard.sentToCoach": "यह अनुमोदन के लिए फील्ड कोच को भेजा जाएगा।",
    "dashboard.reasonForDeactivation": "निष्क्रियता का कारण",
    "dashboard.enterReason": "निष्क्रियता का कारण दर्ज करें...",
    "dashboard.submitRequest": "अनुरोध सबमिट करें",
    "dashboard.close": "बंद करें",
    "dashboard.draft": "ड्राफ्ट",
    "dashboard.submitted": "सबमिट किया गया",
    "dashboard.active": "सक्रिय",
    "dashboard.inactive": "निष्क्रिय",
    "dashboard.pendingDeactivation": "निष्क्रियता लंबित",
    "dashboard.statusDraft": "कर्मचारी ने ऑनबोर्डिंग फॉर्म शुरू किया है लेकिन पूरा नहीं किया है।",
    "dashboard.statusInProgress": "कर्मचारी वर्तमान में ऑनबोर्डिंग प्रक्रिया पूरी कर रहा है।",
    "dashboard.statusSubmitted": "ऑनबोर्डिंग फॉर्म सबमिट किया गया है और समीक्षा की प्रतीक्षा में है।",
    "dashboard.statusPendingApproval": "फील्ड कोच अनुमोदन की प्रतीक्षा में।",
    "dashboard.statusApproved": "ऑनबोर्डिंग स्वीकृत हो गई है!",
    "dashboard.statusRejected": "ऑनबोर्डिंग फील्ड कोच द्वारा अस्वीकार कर दी गई।",
    "dashboard.nextStepDraft": "कर्मचारी को ऑनबोर्डिंग फॉर्म पूरा करके सबमिट करना होगा।",
    "dashboard.nextStepInProgress": "कर्मचारी को सभी ऑनबोर्डिंग चरण पूरे करने होंगे।",
    "dashboard.nextStepSubmitted": "आवेदन फील्ड कोच द्वारा समीक्षाधीन है।",
    "dashboard.nextStepPendingApproval": "फील्ड कोच जल्द ही इस आवेदन की समीक्षा करेगा।",
    "dashboard.nextStepApproved": "यह कर्मचारी अब LMS एक्सेस कर सकता है और काम शुरू कर सकता है।",
    "dashboard.nextStepRejected": "आपको अधिक जानकारी के लिए फील्ड कोच से संपर्क करना होगा या ऑनबोर्डिंग प्रक्रिया फिर से शुरू करनी होगी।",
    "dashboard.pendingReview": "समीक्षा लंबित",
    "dashboard.onboardingApprovals": "ऑनबोर्डिंग स्वीकृतियां",
    "dashboard.searchByNamePhoneOutlet": "नाम, फोन या आउटलेट से खोजें...",
    "dashboard.all": "सभी",
    "dashboard.aadhaarVerified": "आधार सत्यापित",
    "dashboard.panVerified": "पैन सत्यापित",
    "dashboard.aadhaarNotVerified": "आधार सत्यापित नहीं",
    "dashboard.viewFullDetails": "पूर्ण विवरण देखें",
    "dashboard.viewDocuments": "दस्तावेज़ देखें",
    "dashboard.requestedBy": "द्वारा अनुरोध किया गया",
    "dashboard.date": "तारीख",
    "dashboard.reason": "कारण",
    "dashboard.approveApplication": "आवेदन स्वीकृत करें",
    "dashboard.rejectApplication": "आवेदन अस्वीकार करें",
    "dashboard.approvingCreatesLMS": "{name} के आवेदन को स्वीकृत करने से उनका LMS खाता स्वचालित रूप से बन जाएगा।",
    "dashboard.provideRejectionReason": "कृपया {name} के आवेदन को अस्वीकार करने का कारण प्रदान करें।",
    "dashboard.enterRejectionReason": "अस्वीकृति का कारण दर्ज करें...",
    "dashboard.approveAndCreateLMS": "स्वीकृत करें और LMS बनाएं",
    "dashboard.approveDeactivation": "निष्क्रियता स्वीकृत करें",
    "dashboard.rejectDeactivation": "निष्क्रियता अस्वीकार करें",
    "dashboard.approvingDeactivatesLMS": "स्वीकृत करने से {name} का LMS खाता निष्क्रिय हो जाएगा।",
    "dashboard.rejectingKeepsActive": "अस्वीकार करने से {name} का खाता सक्रिय रहेगा।",
    "dashboard.enterReasonForRejection": "अस्वीकृति का कारण दर्ज करें...",
    "dashboard.completeApplicationDetails": "पूर्ण आवेदन विवरण",
    "dashboard.fullInformationFor": "के लिए पूर्ण जानकारी",
    "dashboard.personalInformation": "व्यक्तिगत जानकारी",
    "dashboard.gender": "लिंग",
    "dashboard.dateOfBirth": "जन्म तिथि",
    "dashboard.maritalStatus": "वैवाहिक स्थिति",
    "dashboard.bloodGroup": "रक्त समूह",
    "dashboard.notProvided": "प्रदान नहीं किया गया",
    "dashboard.contactInformation": "संपर्क जानकारी",
    "dashboard.phone1": "फोन 1",
    "dashboard.phone2": "फोन 2",
    "dashboard.verified": "सत्यापित",
    "dashboard.currentAddress": "वर्तमान पता",
    "dashboard.permanentAddress": "स्थायी पता",
    "dashboard.education": "शिक्षा",
    "dashboard.qualification": "योग्यता",
    "dashboard.specialization": "विशेषज्ञता",
    "dashboard.educationStatus": "स्थिति",
    "dashboard.workExperience": "कार्य अनुभव",
    "dashboard.totalExperience": "कुल अनुभव",
    "dashboard.years": "वर्ष",
    "dashboard.lastDesignation": "अंतिम पदनाम",
    "dashboard.employmentDetails": "रोजगार विवरण",
    "dashboard.store": "स्टोर",
    "dashboard.storeCode": "स्टोर कोड",
    "dashboard.storeName": "स्टोर का नाम",
    "dashboard.dateOfJoining": "शामिल होने की तारीख",
    "dashboard.fieldCoach": "फील्ड कोच",
    "dashboard.idVerification": "आईडी और सत्यापन",
    "dashboard.aadhaar": "आधार",
    "dashboard.pan": "पैन",
    "dashboard.uniformSize": "यूनिफ़ॉर्म साइज",
    "dashboard.tshirt": "टी-शर्ट",
    "dashboard.lower": "लोअर",
    "dashboard.vaccinationStatus": "टीकाकरण स्थिति",
    "dashboard.covidVaccinated": "COVID-19 टीकाकरण",
    "dashboard.covidNotVaccinated": "COVID-19 टीकाकरण नहीं",
    "dashboard.previousEmploymentHistory": "पिछला रोजगार इतिहास",
    "dashboard.workedPreviously": "यह आवेदक पहले बर्गर सिंह में काम कर चुका है। नीचे उनके रोजगार इतिहास की समीक्षा करें।",
    "dashboard.deactivated": "निष्क्रिय",
    "dashboard.terminated": "समाप्त",
    "dashboard.cancel": "रद्द करें",
    "dashboard.email": "ईमेल",

    // Admin
    "admin.title": "एडमिन डैशबोर्ड",
    "admin.dashboard": "डैशबोर्ड",
    "admin.employees": "कर्मचारी",
    "admin.outlets": "आउटलेट",
    "admin.fieldCoaches": "फील्ड कोच",
    "admin.roles": "भूमिकाएं",
    "admin.settings": "सेटिंग्स",
    "admin.superAdmin": "सुपर एडमिन",
    "admin.totalUsers": "कुल उपयोगकर्ता",
    "admin.pendingApprovals": "लंबित स्वीकृतियां",
    "admin.activeOutlets": "सक्रिय आउटलेट",
    "admin.totalRoles": "कुल भूमिकाएं",
    "admin.quickActions": "त्वरित क्रियाएं",
    "admin.manageOutlets": "आउटलेट प्रबंधित करें",
    "admin.manageRoles": "भूमिकाएं प्रबंधित करें",
    "admin.viewEmployees": "कर्मचारी देखें",
    "admin.exportData": "डेटा निर्यात करें",
    "admin.recentOutlets": "हालिया आउटलेट",
    "admin.roleDistribution": "भूमिका वितरण",
    "admin.users": "उपयोगकर्ता",
    "admin.allUsers": "सभी उपयोगकर्ता",
    "admin.longPending": "लंबे समय से लंबित",
    "admin.missingDocs": "दस्तावेज़ गायब",
    "admin.rehire": "पुनः नियुक्त करें",
    "admin.searchPlaceholder": "नाम, फोन, आधार या पैन से खोजें...",
    "admin.allStores": "सभी स्टोर",
    "admin.store": "स्टोर",
    "admin.allCoaches": "सभी कोच",
    "admin.allStatus": "सभी स्थिति",
    "admin.exportCSV": "CSV निर्यात करें",
    "admin.exportUsers": "उपयोगकर्ता निर्यात करें",
    "admin.loadingEmployees": "कर्मचारी लोड हो रहे हैं...",
    "admin.employee": "कर्मचारी",
    "admin.contact": "संपर्क",
    "admin.verification": "सत्यापन",
    "admin.actions": "कार्रवाई",
    "admin.copyEmployeeURL": "कर्मचारी URL कॉपी करें",
    "admin.initiateRehire": "पुनः नियुक्ति शुरू करें",
    "admin.deactivate": "निष्क्रिय करें",
    "admin.terminate": "समाप्त करें",
    "admin.noEmployeesFound": "कोई कर्मचारी नहीं मिला",
    "admin.addOutlet": "आउटलेट जोड़ें",
    "admin.outletName": "आउटलेट का नाम",
    "admin.code": "कोड",
    "admin.employeeCount": "कर्मचारी संख्या",
    "admin.createdOn": "बनाया गया",
    "admin.assignFieldCoach": "फील्ड कोच असाइन करें",
    "admin.noFieldCoachAssigned": "कोई फील्ड कोच असाइन नहीं",
    "admin.editOutlet": "आउटलेट संपादित करें",
    "admin.deleteOutlet": "आउटलेट हटाएं",
    "admin.noOutletsFound": "कोई आउटलेट नहीं मिला",
    "admin.addFieldCoach": "फील्ड कोच जोड़ें",
    "admin.assignedOutlets": "असाइन किए गए आउटलेट",
    "admin.noOutletsAssigned": "कोई आउटलेट असाइन नहीं",
    "admin.editFieldCoach": "फील्ड कोच संपादित करें",
    "admin.deleteFieldCoach": "फील्ड कोच हटाएं",
    "admin.noFieldCoachesFound": "कोई फील्ड कोच नहीं मिला",
    "admin.addRole": "भूमिका जोड़ें",
    "admin.description": "विवरण",
    "admin.userCount": "उपयोगकर्ता संख्या",
    "admin.created": "बनाया गया",
    "admin.editRole": "भूमिका संपादित करें",
    "admin.deleteRole": "भूमिका हटाएं",
    "admin.noRolesFound": "कोई भूमिका नहीं मिली",
    "admin.terminateEmployee": "कर्मचारी समाप्त करें",
    "admin.terminatingWarning": "{name} को समाप्त करने से उनका खाता और LMS एक्सेस स्थायी रूप से निष्क्रिय हो जाएगा। यह क्रिया पूर्ववत नहीं की जा सकती।",
    "admin.terminationReason": "समाप्ति का कारण",
    "admin.deactivateEmployee": "कर्मचारी निष्क्रिय करें",
    "admin.deactivatingWarning": "{name} को निष्क्रिय करने से उनका खाता और LMS एक्सेस निलंबित हो जाएगा। उन्हें बाद में फिर से नियुक्त किया जा सकता है।",
    "admin.deactivationReason": "निष्क्रियता का कारण",
    "admin.createOutlet": "आउटलेट बनाएं",
    "admin.outletInformation": "आउटलेट जानकारी",
    "admin.enterOutletName": "आउटलेट का नाम दर्ज करें",
    "admin.enterOutletCode": "आउटलेट कोड दर्ज करें (उदा., BS-CP-001)",
    "admin.enterEmail": "ईमेल दर्ज करें",
    "admin.enterPassword": "पासवर्ड दर्ज करें",
    "admin.enterPhone": "फोन नंबर दर्ज करें",
    "admin.address": "पता",
    "admin.enterAddress": "पता दर्ज करें",
    "admin.city": "शहर",
    "admin.enterCity": "शहर दर्ज करें",
    "admin.state": "राज्य",
    "admin.enterState": "राज्य दर्ज करें",
    "admin.pincode": "पिनकोड",
    "admin.enterPincode": "पिनकोड दर्ज करें",
    "admin.selectFieldCoach": "फील्ड कोच चुनें",
    "admin.none": "कोई नहीं",
    "admin.create": "बनाएं",
    "admin.update": "अपडेट करें",
    "admin.updateOutlet": "आउटलेट अपडेट करें",
    "admin.deleteOutletConfirm": "क्या आप वाकई {name} को हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
    "admin.createFieldCoach": "फील्ड कोच बनाएं",
    "admin.fieldCoachInformation": "फील्ड कोच जानकारी",
    "admin.enterName": "नाम दर्ज करें",
    "admin.noOutletsAvailable": "कोई आउटलेट उपलब्ध नहीं",
    "admin.updateFieldCoach": "फील्ड कोच अपडेट करें",
    "admin.deleteFieldCoachConfirm": "क्या आप वाकई {name} को हटाना चाहते हैं? सभी असाइन किए गए आउटलेट अनअसाइन हो जाएंगे।",
    "admin.createRole": "भूमिका बनाएं",
    "admin.roleInformation": "भूमिका जानकारी",
    "admin.roleName": "भूमिका का नाम",
    "admin.enterRoleName": "भूमिका का नाम दर्ज करें",
    "admin.roleDescription": "भूमिका विवरण",
    "admin.enterRoleDescription": "भूमिका विवरण दर्ज करें",
    "admin.updateRole": "भूमिका अपडेट करें",
    "admin.deleteRoleConfirm": "क्या आप वाकई {name} भूमिका को हटाना चाहते हैं?",
    "admin.uploadedDocuments": "अपलोड किए गए दस्तावेज़",
    "admin.allDocumentsSubmitted": "{name} द्वारा सबमिट किए गए सभी दस्तावेज़",
    "admin.livePhoto": "लाइव फोटो",
    "admin.clickToOpenFullSize": "पूर्ण आकार में खोलने के लिए क्लिक करें",
    "admin.educationCertificate": "शिक्षा प्रमाणपत्र",
    "admin.experienceDocument": "अनुभव दस्तावेज़",
    "admin.idDocuments": "आईडी दस्तावेज़ (आधार/पैन कॉपी)",
    "admin.panDocument": "पैन दस्तावेज़",
    "admin.otherCertificates": "अन्य प्रमाणपत्र",
    "admin.noDocumentsUploaded": "कोई दस्तावेज़ अपलोड नहीं किया गया",

    // Errors
    "error.pageNotFound": "ओह! पृष्ठ नहीं मिला",
    "error.unauthorized": "एक्सेस अस्वीकृत",
    "error.somethingWentWrong": "लगता है यह पेज बर्गर ब्रेक पर चला गया। आइए आपको वापस ट्रैक पर लाते हैं!",
    "error.tryAgain": "फिर से कोशिश करें",
    "error.goHome": "होम पेज",
    "error.contactSupport": "आपके पास इस पेज तक पहुंचने की अनुमति नहीं है। यदि आपको लगता है कि यह एक त्रुटि है, तो कृपया अपने प्रशासक से संपर्क करें।",
  },
};
